import type { Metadata } from "next";
import type { ReactNode } from "react";
import { notFound } from "next/navigation";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { getLangDir } from "rtl-detect";
import { routing } from "@/i18n/routing";
import { Theme } from "@/store";
import { Toaster, TooltipProvider } from "@/components/ui";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }: { children: ReactNode; params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  const dir = getLangDir(locale);

  return (
    <html lang={locale} dir={dir} suppressHydrationWarning>
      <body>
        <NextIntlClientProvider>
          <Theme attribute="class" defaultTheme="system" themes={["light", "dark"]} enableSystem disableTransitionOnChange>
            <TooltipProvider>
              {children}
              <Toaster position={dir == "ltr" ? "bottom-right" : "bottom-left"} duration={10000} richColors closeButton />
            </TooltipProvider>
          </Theme>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
